@echo off
echo Starting git push process...
echo Starting git push process... > git_log.txt

echo 1. Initializing git...
git init >> git_log.txt 2>&1
echo 2. Adding files...
git add . >> git_log.txt 2>&1
echo 3. Committing code...
git commit -m "Initial project commit" >> git_log.txt 2>&1
echo 4. Renaming branch...
git branch -M main >> git_log.txt 2>&1
echo 5. Removing old remote (if exists)...
git remote remove origin >> git_log.txt 2>&1
echo 6. Adding new remote...
git remote add origin https://github.com/AkshayaTulasi08/Fraudapp-detection1.git >> git_log.txt 2>&1
echo 7. Pushing to GitHub...
git push -u origin main >> git_log.txt 2>&1

echo.
echo Process finished! 
echo Please check the file "git_log.txt" in your folder to see what went wrong, or tell me and I can read it!
pause
